
DROP TABLE IF EXISTS ACTIONMOVIE;

CREATE TABLE IF NOT EXISTS ACTIONMOVIE (
   id SERIAL PRIMARY KEY,
    title VARCHAR(255),
    release_date VARCHAR(255),
    poster_path VARCHAR(255),
    overview VARCHAR(3000)

);
